# Generated by Django 6.0.3 on 2026-06-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_product_brand_product_description_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='39,40,41,42,43,44,45', max_length=255),
        ),
    ]
